### ISSUE TITLE
Turbo buttons

### ISSUE THREAD

**Issue by UzixLS** [mist-devel/nes#3]
Hi.
It's possible to bind X and Y keys as turbo (aka autofire) variants of A and B?
Almost 100% of Dendy consoles have turbo buttons and there is official gamepads for Famicom with turbo buttons (NES Max and BPS Max controllers).
I'm ready to implement it my own and propose pull request.

**Comment by gyurco** [comment]
The autofire mode selectable via the ctrl+alt+ins combo is not enough? Or you need both non-turbo and turbo keys at the same time (I admit, that can be useful in some cases)?

**Comment by UzixLS** [comment]
Yes, I'm talking about turbo and non turbo buttons available at the same time.

**Comment by gyurco** [comment]
Ah, OK, then go ahead if you want :)
